server:
  port: ${PORT:${SERVER_PORT:0}}
info:
  id: ${spring.application.name}
logging:
  level: debug  
  
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
  security:
    basic:
    enabled: false 
  server:
    port: ${PORT:8000}
