server:
  port: 8080
  
spring:
  application:
    name: usuario-service
  cloud: 
    discovery:
      client:
        simple:
          local:
            uri: http://localhost:8888
              
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none  
  datasource:
    url: jdbc:oracle:thin:@stargate:1521:dadmtse
    username: acesso
    password: acesso
    driver-class-name: oracle.jdbc.driver.OracleDriver        
      
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true          
