server:
  port: 8082

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: condominio-service
  cloud: 
    discovery:
      client:
        simple:
          local:
            uri: http://localhost:8888              
  jpa:
    database-platform: br.com.condominio.client.SQLiteDialect
    show-sql: true
    hibernate:
      ddl-auto: none  
  datasource:
    driver-class-name: org.sqlite.JDBC      
    hikari:
      jdbc-url: jdbc:sqlite:E:\Desenvolvimento\Repositorios\Ionic\condominio\src\app\db\admcond.db 
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false  
eureka:
  client:
    register-with-eureka: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
    hostname: localhost