server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: file://D:\Desenvolvimento\Repositorios\Java\Java\config-repo