server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: file://D:\Desenvolvimento\Java\workspace\workspace-sts-3.9.0.RELEASE\config-repo