server:
  port: 8888

management:
  security:
    enabled: false

spring:
  cloud:
    config:
      server:
        git:
          uri: file:///E:\Desenvolvimento\Repositorios\Java\java-microservices\config-repo